name: Selenium Selectors Tests

on: [push]

env:
  DB_CONNECTION_STRING: "./data/tabular/wdb_crawler.csv"
  INSTAGRAM_USERNAME: "wdb_crawler"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with unittest
        env: # Or as an environment variable
          super_secret: ${{ secrets.INSTAGRAM_PASSWORD }}
        run: |
          python -m unittest discover -p 'test_*.py'